### ISSUE TITLE
Native Lux Sensor Integration for Automated Blind Control

### ISSUE THREAD

**Issue by coasttech** [jo-ket/compact-cover-control-card#2]
Feature Request:

I actively use lux sensors to determine when my blinds should open or close based on ambient light levels. It would be great to see native support for this within the Compact Cover Control Card.

The feature should allow users to set lux thresholds for opening and closing blinds automatically. Additionally, a time-based logic should be incorporated to prevent unnecessary toggling—ensuring that if the lux threshold is met at a given time, the blinds only move if they haven’t already reached the desired position.

For example:
	•	If the lux level exceeds the open threshold during the day, the blinds should open—unless they are already open.
	•	If the lux level drops below the close threshold in the evening, the blinds should close—unless they are already closed.

This would make the card even more powerful for automation without requiring separate Home Assistant automations.

Would love to see this implemented! Thanks for the great work. 🚀

**Comment by jo-ket** [comment]
Thanks for the input. I will give it a try as soon as I find some free time.

**Comment by jo-ket** [comment]
I could imagine a config on three levels. Global, room and cover, the top example shows the full config. If it is between 10:30 and 19:30 and the brightness is between 1000 and 10000 lux all blinds go to 65%. 
What do you think about this basic idea? However, did not think about the real implementation part yet.

```yaml
# Global level
lux_automation:
  - entity: sensor.outdoor_lux
    above: 1000
    below: 10000
    position: 65
    after:
      hour: 10
      minute: 30
    before:
      hour: 19
      minute: 30
  - entity: sensor.outdoor_lux
    below: 500
    position: 0    # Close completely when dark
    after:
      hour: 19
      minute: 30

# Room level (overrides or adds to global)
rooms:
  - name: Living Room
    lux_automation:
      - entity: sensor.living_room_lux
        above: 15000
        position: 20    # Partial close for bright sun
    covers:
      - name: South Window
        entity: cover.living_south
        # Cover specific (adds to or overrides room/global)
        lux_automation:
          - entity: sensor.window_lux
            above: 20000
            position: 0  # Full close for extreme brightness
```
